root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  # full_bin = "dlv exec ./tmp/main --headless --listen=:2345 --api-version=2 --accept-multiclient"
  cmd = "npm run build && go tool templ generate && CGO_CFLAGS=\"-DHAVE_STRCHRNUL -mmacosx-version-min=15.4\" MACOSX_DEPLOYMENT_TARGET=\"15.4\" go tool sqlc generate && go build -gcflags=\"all=-N -l\" -o ./tmp/main ."
  # cmd = "templ generate && sqlc generate && go build -gcflags=\"all=-N -l\" -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test\\.go", ".*_templ\\.go", "db\\/.+?[^_]+"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ", "html", "sql", "ts"]
  include_file = []
  kill_delay = 500
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = true
  app_port = 42069
  proxy_port = 42169

[screen]
  clear_on_rebuild = false
  keep_scroll = true
