// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pricecalc

type Ingredient struct {
	ID   int64
	Name string
}

type IngredientPrice struct {
	ID           int64
	Price        float64
	IngredientID int64
}
