name: Generate SQLC + Templ Code
description: Installs tools and runs codegen
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
    - run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      shell: bash
    - run: go install github.com/a-h/templ/cmd/templ@latest
      shell: bash
    - run: sqlc generate && templ generate
      shell: bash

