// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Category struct {
	ID   int64
	Name string
	Vat  int64
}

type Ingredient struct {
	ID   int64
	Name string
}

type IngredientPrice struct {
	ID           int64
	TimeStamp    int64
	Price        float64
	Quantity     float64
	UnitID       int64
	IngredientID int64
}

type IngredientUsage struct {
	ID           int64
	Quantity     float64
	UnitID       int64
	IngredientID int64
	ProductID    int64
}

type Product struct {
	ID         int64
	Name       string
	CategoryID *int64
}

type Unit struct {
	ID         int64
	Name       string
	BaseUnitID *int64
	Factor     interface{}
}
