// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Vat  int64  `json:"vat"`
}

type Ingredient struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type IngredientPrice struct {
	ID            int64    `json:"id"`
	TimeStamp     int64    `json:"time_stamp"`
	Price         *float64 `json:"price"`
	Quantity      float64  `json:"quantity"`
	UnitID        int64    `json:"unit_id"`
	IngredientID  int64    `json:"ingredient_id"`
	BaseProductID *int64   `json:"base_product_id"`
}

type IngredientUsage struct {
	ID           int64   `json:"id"`
	Quantity     float64 `json:"quantity"`
	UnitID       int64   `json:"unit_id"`
	IngredientID int64   `json:"ingredient_id"`
	ProductID    int64   `json:"product_id"`
}

type Product struct {
	ID            int64   `json:"id"`
	Name          string  `json:"name"`
	Price         float64 `json:"price"`
	Multiplicator float64 `json:"multiplicator"`
	CategoryID    int64   `json:"category_id"`
}

type ProductCostCache struct {
	ProductID int64   `json:"product_id"`
	Cost      float64 `json:"cost"`
}

type Unit struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	BaseUnitID *int64  `json:"base_unit_id"`
	Factor     float64 `json:"factor"`
}
