name: Generate SQLC + Templ Code
description: Installs tools and runs codegen
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.28.0'

    - name: Pre-download Go modules
      run: go mod download
      shell: bash

    - name: Generate sqlc
      run: sqlc generate
      shell: bash

    - name: Generate templ
      run: go tool templ generate
      shell: bash
