name: Generate SQLC + Templ Code
description: Installs tools and runs codegen
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Clean Go mod + build cache before restore
      run: |
        sudo rm -rf ~/go/pkg/mod || true
        sudo rm -rf ~/.cache/go-build || true
      shell: bash

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - run: go tool sqlc generate
      shell: bash

    - run: go tool templ generate
      shell: bash
