name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push to GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "Tagged version: $TAG"
            echo "image_tag=$TAG" >> $GITHUB_OUTPUT
            echo "tagged_version=true" >> $GITHUB_OUTPUT
            echo "image_tags<<EOF" >> $GITHUB_OUTPUT
            echo "$IMAGE:$TAG" >> $GITHUB_OUTPUT
            echo "$IMAGE:latest" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "Defaulting to 'dev'"
            echo "image_tag=dev" >> $GITHUB_OUTPUT
            echo "tagged_version=false" >> $GITHUB_OUTPUT
            echo "image_tags=$IMAGE:dev" >> $GITHUB_OUTPUT
          fi
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.image_tags }}
          platforms: linux/amd64,linux/arm64

