name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          TAGS=()
          
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS+=("${IMAGE}:${VERSION}")
            TAGS+=("${IMAGE}:latest")
          else
            SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            TAGS+=("${IMAGE}:${SHORT_SHA}")
            TAGS+=("${IMAGE}:dev")
          fi

          echo "tags=${TAGS[*]}" >> $GITHUB_OUTPUT
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.image_tags }}
          platforms: linux/amd64,linux/arm64

